# Generated by Django 6.0.5 on 2026-05-28 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DuneBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Book Title')),
                ('author', models.CharField(default='Frank Herbert', max_length=100)),
                ('planet', models.CharField(max_length=100, verbose_name='Planet')),
                ('house', models.CharField(max_length=100, verbose_name='Noble House')),
                ('main_character', models.CharField(max_length=100, verbose_name='Main Character')),
                ('genre', models.CharField(max_length=100, verbose_name='Genre')),
                ('short_description', models.TextField(verbose_name='Short Description')),
                ('full_description', models.TextField(verbose_name='Full Description')),
                ('publication_year', models.PositiveIntegerField(verbose_name='Publication Year')),
                ('reservation_count', models.PositiveIntegerField(default=0, help_text='You can reserve this book up to 5 times.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Reservation Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('can_be_bought_url', models.URLField(blank=True, null=True, verbose_name='Can Be Bought URL')),
            ],
        ),
    ]
