# Generated by Django 6.0.5 on 2026-06-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_dunebook_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='dunebook',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
