# Generated by Django 6.0.5 on 2026-06-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title of the movie')),
                ('year', models.PositiveIntegerField(verbose_name='The year this movie came out')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ConeBoard/photos/')),
                ('genre', models.CharField(max_length=50, verbose_name='The genre of the movie')),
                ('creator', models.CharField(max_length=100, verbose_name='Name of the creator')),
                ('describtion', models.TextField(blank=True, null=True, verbose_name='Describtion of the movie')),
                ('score', models.IntegerField(verbose_name='The combined score of the movie')),
                ('do_recommend', models.BooleanField(default=False, verbose_name='Do you recommend?')),
                ('country_of_prodaction', models.CharField(max_length=100, verbose_name='Where it was created')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
