# Generated by Django 6.0.5 on 2026-06-16 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CineBoard', '0002_alter_movie_photo_comment_vipseat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vipseat',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='vipseat',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='VipSeat',
        ),
    ]
