# Generated by Django 6.0.5 on 2026-06-06 12:44

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anket',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ankets2/photos/')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('previous_experience', models.CharField(max_length=200)),
                ('recommendation', models.CharField(max_length=200)),
                ('reason_to_join', models.CharField(max_length=200)),
                ('hours_per_week', models.IntegerField()),
                ('satisfaction_level', models.IntegerField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
