# Generated by Django 6.0.5 on 2026-06-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankets2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anket',
            name='views',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
    ]
