# Generated by Django 6.0.5 on 2026-05-31 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racer',
            name='horse',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='horsetourcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='horsetour',
            name='price',
        ),
        migrations.RemoveField(
            model_name='horsetourcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='person',
            name='phone',
        ),
        migrations.AddField(
            model_name='horse',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horse', to='race.person', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='person',
            name='personal_number',
            field=models.CharField(max_length=20, verbose_name='Персональный номер'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Racer',
        ),
    ]
