# Generated by Django 6.0.5 on 2026-06-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0002_remove_racer_horse_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horsetour',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
